const INHERITED_AGENT_RUNTIME_ENV_KEYS = [
  "AGENT_HOME",
  "PAPERCLIP_AGENT_ID",
  "PAPERCLIP_COMPANY_ID",
  "PAPERCLIP_API_KEY",
  "PAPERCLIP_API_URL",
  "PAPERCLIP_RUN_ID",
  "PAPERCLIP_TASK_ID",
  "PAPERCLIP_WAKE_REASON",
  "PAPERCLIP_WAKE_COMMENT_ID",
  "PAPERCLIP_APPROVAL_ID",
  "PAPERCLIP_APPROVAL_STATUS",
  "PAPERCLIP_LINKED_ISSUE_IDS",
  "PAPERCLIP_WAKE_PAYLOAD_JSON",
  "PAPERCLIP_WORKSPACE_CWD",
  "PAPERCLIP_WORKSPACE_SOURCE",
  "PAPERCLIP_WORKSPACE_STRATEGY",
  "PAPERCLIP_WORKSPACE_ID",
  "PAPERCLIP_WORKSPACE_REPO_URL",
  "PAPERCLIP_WORKSPACE_REPO_REF",
  "PAPERCLIP_WORKSPACE_BRANCH",
  "PAPERCLIP_WORKSPACE_WORKTREE_PATH",
  "PAPERCLIP_WORKSPACES_JSON",
  "PAPERCLIP_RUNTIME_SERVICE_INTENTS_JSON",
  "PAPERCLIP_RUNTIME_SERVICES_JSON",
  "PAPERCLIP_RUNTIME_PRIMARY_URL",
];

export function sanitizeInheritedAgentRuntimeEnv(env: NodeJS.ProcessEnv = process.env) {
  for (const key of INHERITED_AGENT_RUNTIME_ENV_KEYS) {
    delete env[key];
  }
}

